import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Nav from '../components/nav';
import Hero from '../components/hero';
import Footer from '../components/footer';

interface BlogListProps {
  data: {
    userId: number;
    id: number;
    title: string;
    body: string;
  }[];
}

const Home = ({ data }: BlogListProps) => {
  return (
    <div className="px-6">
      <div className="flex flex-col min-h-screen max-w-screen-md mx-auto">
        <Head>
          <title>Blog Pribadi Dimas Kurniawan</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <Nav />
        <Hero />
        <main className="mt-10">
          <h1 className="text-3xl font-bold mb-4 md:px-5">Tulisan Terbaru</h1>
          <div className="grid">
            {data.map(({ id, title }) => (
              <a
                key={id}
                href=""
                className="capitalize rounded-sm py-2 md:px-5 md:hover:bg-gray-200 md:hover:text-gray-900 text-gray-700"
              >
                {title}
              </a>
            ))}
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts');
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};

export default Home;
