import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../components/nav';
import Hero from '../components/hero';
import Footer from '../components/footer';

const Home: NextPage = () => {
  return (
    <div className="px-6">
      <div className="flex flex-col min-h-screen max-w-screen-md mx-auto">
        <Head>
          <title>Blog Pribadi Dimas Kurniawan</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <Nav />
        <Hero />
        <Footer />
      </div>
    </div>
  );
};

export default Home;
